# Generated by Django 4.2.4 on 2023-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson', '0002_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=20, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Стоимость урока'),
        ),
    ]
