# Generated by Django 4.2.4 on 2023-09-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платёж', 'verbose_name_plural': 'платежи'},
        ),
    ]
