# Generated by Django 4.2.4 on 2023-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=255, verbose_name='Валюта'),
        ),
    ]
